stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_prep.py
    deps:
    - data/raw
    - src/data_prep.py
    outs:
    - data/processed
  model_building:
    cmd: python src/modeling/model_building.py
    deps:
    - data/processed
    - src/modeling/model_building.py
    params:
    - model_building.n_estimators
    - model_building.max_depth
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/modeling/model_evaluation.py
    deps:
    - data/processed
    - models/model.pkl
    - src/modeling/model_evaluation.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/run_info.json
  model_registration:
    cmd: python src/modeling/model_register.py
    deps:
    - reports/run_info.json
    - src/modeling/model_register.py


